name: Rust Contracts

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install toolchain for test contracts
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.69.0

      - name: add wasm32-unknown-unknown
        run: rustup target add wasm32-unknown-unknown

      - name: cargo test
        run: cargo test --all --all-features

  lint:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true

      - name: cargo fmt
        run: cargo fmt --all -- --check

      - name: cargo clippy
        run: cargo clippy --all --all-features --all-targets -- -D warnings
